spring:

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

pagehelper:
  helper-dialect: mysql    #使用的数据库. mysql, oracle, sqlite
  reasonable: true #开启优化,在分页页码结果没有数据的时候,会显示有数据的页码数据,也就是当当前页<1时,返回第 1 页, 当前页 > 最大页时, 返回最后一页的数据.
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #表示当 pageSize=0 时返回所有
  params: count=countSql


