package com.project.smartcharge.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public BillExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBillIDIsNull() {
            addCriterion("BillID is null");
            return (Criteria) this;
        }

        public Criteria andBillIDIsNotNull() {
            addCriterion("BillID is not null");
            return (Criteria) this;
        }

        public Criteria andBillIDEqualTo(Integer value) {
            addCriterion("BillID =", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDNotEqualTo(Integer value) {
            addCriterion("BillID <>", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDGreaterThan(Integer value) {
            addCriterion("BillID >", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("BillID >=", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDLessThan(Integer value) {
            addCriterion("BillID <", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDLessThanOrEqualTo(Integer value) {
            addCriterion("BillID <=", value, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDIn(List<Integer> values) {
            addCriterion("BillID in", values, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDNotIn(List<Integer> values) {
            addCriterion("BillID not in", values, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDBetween(Integer value1, Integer value2) {
            addCriterion("BillID between", value1, value2, "billID");
            return (Criteria) this;
        }

        public Criteria andBillIDNotBetween(Integer value1, Integer value2) {
            addCriterion("BillID not between", value1, value2, "billID");
            return (Criteria) this;
        }

        public Criteria andChargeModIsNull() {
            addCriterion("chargeMod is null");
            return (Criteria) this;
        }

        public Criteria andChargeModIsNotNull() {
            addCriterion("chargeMod is not null");
            return (Criteria) this;
        }

        public Criteria andChargeModEqualTo(Boolean value) {
            addCriterion("chargeMod =", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModNotEqualTo(Boolean value) {
            addCriterion("chargeMod <>", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModGreaterThan(Boolean value) {
            addCriterion("chargeMod >", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModGreaterThanOrEqualTo(Boolean value) {
            addCriterion("chargeMod >=", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModLessThan(Boolean value) {
            addCriterion("chargeMod <", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModLessThanOrEqualTo(Boolean value) {
            addCriterion("chargeMod <=", value, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModIn(List<Boolean> values) {
            addCriterion("chargeMod in", values, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModNotIn(List<Boolean> values) {
            addCriterion("chargeMod not in", values, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModBetween(Boolean value1, Boolean value2) {
            addCriterion("chargeMod between", value1, value2, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andChargeModNotBetween(Boolean value1, Boolean value2) {
            addCriterion("chargeMod not between", value1, value2, "chargeMod");
            return (Criteria) this;
        }

        public Criteria andCreated_atIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreated_atIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_atEqualTo(Date value) {
            addCriterion("created_at =", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atGreaterThan(Date value) {
            addCriterion("created_at >", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atLessThan(Date value) {
            addCriterion("created_at <", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atIn(List<Date> values) {
            addCriterion("created_at in", values, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "created_at");
            return (Criteria) this;
        }

        public Criteria andCreated_atNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "created_at");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNull() {
            addCriterion("deviceID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNotNull() {
            addCriterion("deviceID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDEqualTo(Integer value) {
            addCriterion("deviceID =", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotEqualTo(Integer value) {
            addCriterion("deviceID <>", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThan(Integer value) {
            addCriterion("deviceID >", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("deviceID >=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThan(Integer value) {
            addCriterion("deviceID <", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThanOrEqualTo(Integer value) {
            addCriterion("deviceID <=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIn(List<Integer> values) {
            addCriterion("deviceID in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotIn(List<Integer> values) {
            addCriterion("deviceID not in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDBetween(Integer value1, Integer value2) {
            addCriterion("deviceID between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotBetween(Integer value1, Integer value2) {
            addCriterion("deviceID not between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andChargeDurationIsNull() {
            addCriterion("chargeDuration is null");
            return (Criteria) this;
        }

        public Criteria andChargeDurationIsNotNull() {
            addCriterion("chargeDuration is not null");
            return (Criteria) this;
        }

        public Criteria andChargeDurationEqualTo(String value) {
            addCriterion("chargeDuration =", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationNotEqualTo(String value) {
            addCriterion("chargeDuration <>", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationGreaterThan(String value) {
            addCriterion("chargeDuration >", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationGreaterThanOrEqualTo(String value) {
            addCriterion("chargeDuration >=", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationLessThan(String value) {
            addCriterion("chargeDuration <", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationLessThanOrEqualTo(String value) {
            addCriterion("chargeDuration <=", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationLike(String value) {
            addCriterion("chargeDuration like", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationNotLike(String value) {
            addCriterion("chargeDuration not like", value, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationIn(List<String> values) {
            addCriterion("chargeDuration in", values, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationNotIn(List<String> values) {
            addCriterion("chargeDuration not in", values, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationBetween(String value1, String value2) {
            addCriterion("chargeDuration between", value1, value2, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeDurationNotBetween(String value1, String value2) {
            addCriterion("chargeDuration not between", value1, value2, "chargeDuration");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeIsNull() {
            addCriterion("chargeStartTime is null");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeIsNotNull() {
            addCriterion("chargeStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeEqualTo(String value) {
            addCriterion("chargeStartTime =", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeNotEqualTo(String value) {
            addCriterion("chargeStartTime <>", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeGreaterThan(String value) {
            addCriterion("chargeStartTime >", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("chargeStartTime >=", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeLessThan(String value) {
            addCriterion("chargeStartTime <", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeLessThanOrEqualTo(String value) {
            addCriterion("chargeStartTime <=", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeLike(String value) {
            addCriterion("chargeStartTime like", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeNotLike(String value) {
            addCriterion("chargeStartTime not like", value, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeIn(List<String> values) {
            addCriterion("chargeStartTime in", values, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeNotIn(List<String> values) {
            addCriterion("chargeStartTime not in", values, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeBetween(String value1, String value2) {
            addCriterion("chargeStartTime between", value1, value2, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeStartTimeNotBetween(String value1, String value2) {
            addCriterion("chargeStartTime not between", value1, value2, "chargeStartTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeIsNull() {
            addCriterion("chargeEndTime is null");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeIsNotNull() {
            addCriterion("chargeEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeEqualTo(String value) {
            addCriterion("chargeEndTime =", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeNotEqualTo(String value) {
            addCriterion("chargeEndTime <>", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeGreaterThan(String value) {
            addCriterion("chargeEndTime >", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("chargeEndTime >=", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeLessThan(String value) {
            addCriterion("chargeEndTime <", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeLessThanOrEqualTo(String value) {
            addCriterion("chargeEndTime <=", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeLike(String value) {
            addCriterion("chargeEndTime like", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeNotLike(String value) {
            addCriterion("chargeEndTime not like", value, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeIn(List<String> values) {
            addCriterion("chargeEndTime in", values, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeNotIn(List<String> values) {
            addCriterion("chargeEndTime not in", values, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeBetween(String value1, String value2) {
            addCriterion("chargeEndTime between", value1, value2, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andChargeEndTimeNotBetween(String value1, String value2) {
            addCriterion("chargeEndTime not between", value1, value2, "chargeEndTime");
            return (Criteria) this;
        }

        public Criteria andUpdated_atIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdated_atIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdated_atEqualTo(Date value) {
            addCriterion("updated_at =", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atLessThan(Date value) {
            addCriterion("updated_at <", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atIn(List<Date> values) {
            addCriterion("updated_at in", values, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updated_at");
            return (Criteria) this;
        }

        public Criteria andUpdated_atNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updated_at");
            return (Criteria) this;
        }

        public Criteria andChargeFeeIsNull() {
            addCriterion("chargeFee is null");
            return (Criteria) this;
        }

        public Criteria andChargeFeeIsNotNull() {
            addCriterion("chargeFee is not null");
            return (Criteria) this;
        }

        public Criteria andChargeFeeEqualTo(Double value) {
            addCriterion("chargeFee =", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeNotEqualTo(Double value) {
            addCriterion("chargeFee <>", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeGreaterThan(Double value) {
            addCriterion("chargeFee >", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("chargeFee >=", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeLessThan(Double value) {
            addCriterion("chargeFee <", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeLessThanOrEqualTo(Double value) {
            addCriterion("chargeFee <=", value, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeIn(List<Double> values) {
            addCriterion("chargeFee in", values, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeNotIn(List<Double> values) {
            addCriterion("chargeFee not in", values, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeBetween(Double value1, Double value2) {
            addCriterion("chargeFee between", value1, value2, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andChargeFeeNotBetween(Double value1, Double value2) {
            addCriterion("chargeFee not between", value1, value2, "chargeFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNull() {
            addCriterion("serviceFee is null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNotNull() {
            addCriterion("serviceFee is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeEqualTo(Double value) {
            addCriterion("serviceFee =", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotEqualTo(Double value) {
            addCriterion("serviceFee <>", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThan(Double value) {
            addCriterion("serviceFee >", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("serviceFee >=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThan(Double value) {
            addCriterion("serviceFee <", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThanOrEqualTo(Double value) {
            addCriterion("serviceFee <=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIn(List<Double> values) {
            addCriterion("serviceFee in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotIn(List<Double> values) {
            addCriterion("serviceFee not in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeBetween(Double value1, Double value2) {
            addCriterion("serviceFee between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotBetween(Double value1, Double value2) {
            addCriterion("serviceFee not between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIDEqualTo(Integer value) {
            addCriterion("userID =", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotEqualTo(Integer value) {
            addCriterion("userID <>", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThan(Integer value) {
            addCriterion("userID >", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("userID >=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThan(Integer value) {
            addCriterion("userID <", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThanOrEqualTo(Integer value) {
            addCriterion("userID <=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDIn(List<Integer> values) {
            addCriterion("userID in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotIn(List<Integer> values) {
            addCriterion("userID not in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDBetween(Integer value1, Integer value2) {
            addCriterion("userID between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotBetween(Integer value1, Integer value2) {
            addCriterion("userID not between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("totalFee is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("totalFee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(Double value) {
            addCriterion("totalFee =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(Double value) {
            addCriterion("totalFee <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(Double value) {
            addCriterion("totalFee >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("totalFee >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(Double value) {
            addCriterion("totalFee <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(Double value) {
            addCriterion("totalFee <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<Double> values) {
            addCriterion("totalFee in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<Double> values) {
            addCriterion("totalFee not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(Double value1, Double value2) {
            addCriterion("totalFee between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(Double value1, Double value2) {
            addCriterion("totalFee not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIsNull() {
            addCriterion("chargeAmount is null");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIsNotNull() {
            addCriterion("chargeAmount is not null");
            return (Criteria) this;
        }

        public Criteria andChargeAmountEqualTo(Integer value) {
            addCriterion("chargeAmount =", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotEqualTo(Integer value) {
            addCriterion("chargeAmount <>", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountGreaterThan(Integer value) {
            addCriterion("chargeAmount >", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("chargeAmount >=", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountLessThan(Integer value) {
            addCriterion("chargeAmount <", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountLessThanOrEqualTo(Integer value) {
            addCriterion("chargeAmount <=", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIn(List<Integer> values) {
            addCriterion("chargeAmount in", values, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotIn(List<Integer> values) {
            addCriterion("chargeAmount not in", values, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountBetween(Integer value1, Integer value2) {
            addCriterion("chargeAmount between", value1, value2, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("chargeAmount not between", value1, value2, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andIsDoneIsNull() {
            addCriterion("isDone is null");
            return (Criteria) this;
        }

        public Criteria andIsDoneIsNotNull() {
            addCriterion("isDone is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoneEqualTo(Boolean value) {
            addCriterion("isDone =", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotEqualTo(Boolean value) {
            addCriterion("isDone <>", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneGreaterThan(Boolean value) {
            addCriterion("isDone >", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isDone >=", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneLessThan(Boolean value) {
            addCriterion("isDone <", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneLessThanOrEqualTo(Boolean value) {
            addCriterion("isDone <=", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneIn(List<Boolean> values) {
            addCriterion("isDone in", values, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotIn(List<Boolean> values) {
            addCriterion("isDone not in", values, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneBetween(Boolean value1, Boolean value2) {
            addCriterion("isDone between", value1, value2, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isDone not between", value1, value2, "isDone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 02 17:49:13 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}