package com.project.smartcharge.pojo;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.BillID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer billID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeMod
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Boolean chargeMod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.created_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer deviceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeDuration
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private String chargeDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeStartTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */

    private String chargeStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeEndTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */

    private String chargeEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.updated_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updated_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Double chargeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.serviceFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Double serviceFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.totalFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Double totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.chargeAmount
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer chargeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.isDone
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Boolean isDone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.BillID
     *
     * @return the value of bill.BillID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getBillID() {
        return billID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.BillID
     *
     * @param billID the value for bill.BillID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setBillID(Integer billID) {
        this.billID = billID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeMod
     *
     * @return the value of bill.chargeMod
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Boolean getChargeMod() {
        return chargeMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeMod
     *
     * @param chargeMod the value for bill.chargeMod
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeMod(Boolean chargeMod) {
        this.chargeMod = chargeMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.created_at
     *
     * @return the value of bill.created_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.created_at
     *
     * @param created_at the value for bill.created_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.deviceID
     *
     * @return the value of bill.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getDeviceID() {
        return deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.deviceID
     *
     * @param deviceID the value for bill.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setDeviceID(Integer deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeDuration
     *
     * @return the value of bill.chargeDuration
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getChargeDuration() {
        return chargeDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeDuration
     *
     * @param chargeDuration the value for bill.chargeDuration
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeDuration(String chargeDuration) {
        this.chargeDuration = chargeDuration == null ? null : chargeDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeStartTime
     *
     * @return the value of bill.chargeStartTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getChargeStartTime() {
        return chargeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeStartTime
     *
     * @param chargeStartTime the value for bill.chargeStartTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeStartTime(String chargeStartTime) {
        this.chargeStartTime = chargeStartTime == null ? null : chargeStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeEndTime
     *
     * @return the value of bill.chargeEndTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getChargeEndTime() {
        return chargeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeEndTime
     *
     * @param chargeEndTime the value for bill.chargeEndTime
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeEndTime(String chargeEndTime) {
        this.chargeEndTime = chargeEndTime == null ? null : chargeEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.updated_at
     *
     * @return the value of bill.updated_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.updated_at
     *
     * @param updated_at the value for bill.updated_at
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeFee
     *
     * @return the value of bill.chargeFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Double getChargeFee() {
        return chargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeFee
     *
     * @param chargeFee the value for bill.chargeFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeFee(Double chargeFee) {
        this.chargeFee = chargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.serviceFee
     *
     * @return the value of bill.serviceFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Double getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.serviceFee
     *
     * @param serviceFee the value for bill.serviceFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setServiceFee(Double serviceFee) {
        this.serviceFee = serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.userID
     *
     * @return the value of bill.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.userID
     *
     * @param userID the value for bill.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.totalFee
     *
     * @return the value of bill.totalFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.totalFee
     *
     * @param totalFee the value for bill.totalFee
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.chargeAmount
     *
     * @return the value of bill.chargeAmount
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.chargeAmount
     *
     * @param chargeAmount the value for bill.chargeAmount
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeAmount(Integer chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.isDone
     *
     * @return the value of bill.isDone
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Boolean getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.isDone
     *
     * @param isDone the value for bill.isDone
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setIsDone(Boolean isDone) {
        this.isDone = isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", billID=").append(billID);
        sb.append(", chargeMod=").append(chargeMod);
        sb.append(", created_at=").append(created_at);
        sb.append(", deviceID=").append(deviceID);
        sb.append(", chargeDuration=").append(chargeDuration);
        sb.append(", chargeStartTime=").append(chargeStartTime);
        sb.append(", chargeEndTime=").append(chargeEndTime);
        sb.append(", updated_at=").append(updated_at);
        sb.append(", chargeFee=").append(chargeFee);
        sb.append(", serviceFee=").append(serviceFee);
        sb.append(", userID=").append(userID);
        sb.append(", totalFee=").append(totalFee);
        sb.append(", chargeAmount=").append(chargeAmount);
        sb.append(", isDone=").append(isDone);
        sb.append("]");
        return sb.toString();
    }
}