package com.project.smartcharge.pojo;

import java.util.ArrayList;
import java.util.List;

public class CarinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public CarinfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarIDIsNull() {
            addCriterion("carID is null");
            return (Criteria) this;
        }

        public Criteria andCarIDIsNotNull() {
            addCriterion("carID is not null");
            return (Criteria) this;
        }

        public Criteria andCarIDEqualTo(Integer value) {
            addCriterion("carID =", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotEqualTo(Integer value) {
            addCriterion("carID <>", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDGreaterThan(Integer value) {
            addCriterion("carID >", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("carID >=", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDLessThan(Integer value) {
            addCriterion("carID <", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDLessThanOrEqualTo(Integer value) {
            addCriterion("carID <=", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDIn(List<Integer> values) {
            addCriterion("carID in", values, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotIn(List<Integer> values) {
            addCriterion("carID not in", values, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDBetween(Integer value1, Integer value2) {
            addCriterion("carID between", value1, value2, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotBetween(Integer value1, Integer value2) {
            addCriterion("carID not between", value1, value2, "carID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNull() {
            addCriterion("deviceID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNotNull() {
            addCriterion("deviceID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDEqualTo(Integer value) {
            addCriterion("deviceID =", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotEqualTo(Integer value) {
            addCriterion("deviceID <>", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThan(Integer value) {
            addCriterion("deviceID >", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("deviceID >=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThan(Integer value) {
            addCriterion("deviceID <", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThanOrEqualTo(Integer value) {
            addCriterion("deviceID <=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIn(List<Integer> values) {
            addCriterion("deviceID in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotIn(List<Integer> values) {
            addCriterion("deviceID not in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDBetween(Integer value1, Integer value2) {
            addCriterion("deviceID between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotBetween(Integer value1, Integer value2) {
            addCriterion("deviceID not between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIDEqualTo(Integer value) {
            addCriterion("userID =", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotEqualTo(Integer value) {
            addCriterion("userID <>", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThan(Integer value) {
            addCriterion("userID >", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("userID >=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThan(Integer value) {
            addCriterion("userID <", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThanOrEqualTo(Integer value) {
            addCriterion("userID <=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDIn(List<Integer> values) {
            addCriterion("userID in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotIn(List<Integer> values) {
            addCriterion("userID not in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDBetween(Integer value1, Integer value2) {
            addCriterion("userID between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotBetween(Integer value1, Integer value2) {
            addCriterion("userID not between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andChargeModeIsNull() {
            addCriterion("chargeMode is null");
            return (Criteria) this;
        }

        public Criteria andChargeModeIsNotNull() {
            addCriterion("chargeMode is not null");
            return (Criteria) this;
        }

        public Criteria andChargeModeEqualTo(Boolean value) {
            addCriterion("chargeMode =", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeNotEqualTo(Boolean value) {
            addCriterion("chargeMode <>", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeGreaterThan(Boolean value) {
            addCriterion("chargeMode >", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("chargeMode >=", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeLessThan(Boolean value) {
            addCriterion("chargeMode <", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeLessThanOrEqualTo(Boolean value) {
            addCriterion("chargeMode <=", value, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeIn(List<Boolean> values) {
            addCriterion("chargeMode in", values, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeNotIn(List<Boolean> values) {
            addCriterion("chargeMode not in", values, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeBetween(Boolean value1, Boolean value2) {
            addCriterion("chargeMode between", value1, value2, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andChargeModeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("chargeMode not between", value1, value2, "chargeMode");
            return (Criteria) this;
        }

        public Criteria andBatterySizeIsNull() {
            addCriterion("batterySize is null");
            return (Criteria) this;
        }

        public Criteria andBatterySizeIsNotNull() {
            addCriterion("batterySize is not null");
            return (Criteria) this;
        }

        public Criteria andBatterySizeEqualTo(Double value) {
            addCriterion("batterySize =", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeNotEqualTo(Double value) {
            addCriterion("batterySize <>", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeGreaterThan(Double value) {
            addCriterion("batterySize >", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeGreaterThanOrEqualTo(Double value) {
            addCriterion("batterySize >=", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeLessThan(Double value) {
            addCriterion("batterySize <", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeLessThanOrEqualTo(Double value) {
            addCriterion("batterySize <=", value, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeIn(List<Double> values) {
            addCriterion("batterySize in", values, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeNotIn(List<Double> values) {
            addCriterion("batterySize not in", values, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeBetween(Double value1, Double value2) {
            addCriterion("batterySize between", value1, value2, "batterySize");
            return (Criteria) this;
        }

        public Criteria andBatterySizeNotBetween(Double value1, Double value2) {
            addCriterion("batterySize not between", value1, value2, "batterySize");
            return (Criteria) this;
        }

        public Criteria andCarDeckIsNull() {
            addCriterion("carDeck is null");
            return (Criteria) this;
        }

        public Criteria andCarDeckIsNotNull() {
            addCriterion("carDeck is not null");
            return (Criteria) this;
        }

        public Criteria andCarDeckEqualTo(String value) {
            addCriterion("carDeck =", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckNotEqualTo(String value) {
            addCriterion("carDeck <>", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckGreaterThan(String value) {
            addCriterion("carDeck >", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckGreaterThanOrEqualTo(String value) {
            addCriterion("carDeck >=", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckLessThan(String value) {
            addCriterion("carDeck <", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckLessThanOrEqualTo(String value) {
            addCriterion("carDeck <=", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckLike(String value) {
            addCriterion("carDeck like", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckNotLike(String value) {
            addCriterion("carDeck not like", value, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckIn(List<String> values) {
            addCriterion("carDeck in", values, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckNotIn(List<String> values) {
            addCriterion("carDeck not in", values, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckBetween(String value1, String value2) {
            addCriterion("carDeck between", value1, value2, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarDeckNotBetween(String value1, String value2) {
            addCriterion("carDeck not between", value1, value2, "carDeck");
            return (Criteria) this;
        }

        public Criteria andCarRankIsNull() {
            addCriterion("carRank is null");
            return (Criteria) this;
        }

        public Criteria andCarRankIsNotNull() {
            addCriterion("carRank is not null");
            return (Criteria) this;
        }

        public Criteria andCarRankEqualTo(Integer value) {
            addCriterion("carRank =", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankNotEqualTo(Integer value) {
            addCriterion("carRank <>", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankGreaterThan(Integer value) {
            addCriterion("carRank >", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("carRank >=", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankLessThan(Integer value) {
            addCriterion("carRank <", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankLessThanOrEqualTo(Integer value) {
            addCriterion("carRank <=", value, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankIn(List<Integer> values) {
            addCriterion("carRank in", values, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankNotIn(List<Integer> values) {
            addCriterion("carRank not in", values, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankBetween(Integer value1, Integer value2) {
            addCriterion("carRank between", value1, value2, "carRank");
            return (Criteria) this;
        }

        public Criteria andCarRankNotBetween(Integer value1, Integer value2) {
            addCriterion("carRank not between", value1, value2, "carRank");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuIsNull() {
            addCriterion("waitingStatu is null");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuIsNotNull() {
            addCriterion("waitingStatu is not null");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuEqualTo(Byte value) {
            addCriterion("waitingStatu =", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuNotEqualTo(Byte value) {
            addCriterion("waitingStatu <>", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuGreaterThan(Byte value) {
            addCriterion("waitingStatu >", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuGreaterThanOrEqualTo(Byte value) {
            addCriterion("waitingStatu >=", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuLessThan(Byte value) {
            addCriterion("waitingStatu <", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuLessThanOrEqualTo(Byte value) {
            addCriterion("waitingStatu <=", value, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuIn(List<Byte> values) {
            addCriterion("waitingStatu in", values, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuNotIn(List<Byte> values) {
            addCriterion("waitingStatu not in", values, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuBetween(Byte value1, Byte value2) {
            addCriterion("waitingStatu between", value1, value2, "waitingStatu");
            return (Criteria) this;
        }

        public Criteria andWaitingStatuNotBetween(Byte value1, Byte value2) {
            addCriterion("waitingStatu not between", value1, value2, "waitingStatu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table carinfo
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 02 17:49:13 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}