package com.project.smartcharge.pojo;

public class Carinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.carID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer carID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer deviceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.chargeMode
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Boolean chargeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.batterySize
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Double batterySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.carDeck
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private String carDeck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.carRank
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Integer carRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.waitingStatu
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    private Byte waitingStatu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.carID
     *
     * @return the value of carinfo.carID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.carID
     *
     * @param carID the value for carinfo.carID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setCarID(Integer carID) {
        this.carID = carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.deviceID
     *
     * @return the value of carinfo.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getDeviceID() {
        return deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.deviceID
     *
     * @param deviceID the value for carinfo.deviceID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setDeviceID(Integer deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.userID
     *
     * @return the value of carinfo.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.userID
     *
     * @param userID the value for carinfo.userID
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.chargeMode
     *
     * @return the value of carinfo.chargeMode
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Boolean getChargeMode() {
        return chargeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.chargeMode
     *
     * @param chargeMode the value for carinfo.chargeMode
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setChargeMode(Boolean chargeMode) {
        this.chargeMode = chargeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.batterySize
     *
     * @return the value of carinfo.batterySize
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Double getBatterySize() {
        return batterySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.batterySize
     *
     * @param batterySize the value for carinfo.batterySize
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setBatterySize(Double batterySize) {
        this.batterySize = batterySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.carDeck
     *
     * @return the value of carinfo.carDeck
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public String getCarDeck() {
        return carDeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.carDeck
     *
     * @param carDeck the value for carinfo.carDeck
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setCarDeck(String carDeck) {
        this.carDeck = carDeck == null ? null : carDeck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.carRank
     *
     * @return the value of carinfo.carRank
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Integer getCarRank() {
        return carRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.carRank
     *
     * @param carRank the value for carinfo.carRank
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setCarRank(Integer carRank) {
        this.carRank = carRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.waitingStatu
     *
     * @return the value of carinfo.waitingStatu
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public Byte getWaitingStatu() {
        return waitingStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.waitingStatu
     *
     * @param waitingStatu the value for carinfo.waitingStatu
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    public void setWaitingStatu(Byte waitingStatu) {
        this.waitingStatu = waitingStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carID=").append(carID);
        sb.append(", deviceID=").append(deviceID);
        sb.append(", userID=").append(userID);
        sb.append(", chargeMode=").append(chargeMode);
        sb.append(", batterySize=").append(batterySize);
        sb.append(", carDeck=").append(carDeck);
        sb.append(", carRank=").append(carRank);
        sb.append(", waitingStatu=").append(waitingStatu);
        sb.append("]");
        return sb.toString();
    }
}