package com.project.smartcharge.pojo;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.deviceID
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Integer deviceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.workingStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Boolean workingStatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.chargeStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Boolean chargeStatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.chargeTimeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private String chargeTimeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.chargeTimesCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Integer chargeTimesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.chargeFeeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Double chargeFeeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.deviceType
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Boolean deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.chargeRate
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    private Integer chargeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.created_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.updated_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.deviceID
     *
     * @return the value of device.deviceID
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Integer getDeviceID() {
        return deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.deviceID
     *
     * @param deviceID the value for device.deviceID
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setDeviceID(Integer deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.workingStatu
     *
     * @return the value of device.workingStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Boolean getWorkingStatu() {
        return workingStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.workingStatu
     *
     * @param workingStatu the value for device.workingStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setWorkingStatu(Boolean workingStatu) {
        this.workingStatu = workingStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.chargeStatu
     *
     * @return the value of device.chargeStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Boolean getChargeStatu() {
        return chargeStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.chargeStatu
     *
     * @param chargeStatu the value for device.chargeStatu
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setChargeStatu(Boolean chargeStatu) {
        this.chargeStatu = chargeStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.chargeTimeCount
     *
     * @return the value of device.chargeTimeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public String getChargeTimeCount() {
        return chargeTimeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.chargeTimeCount
     *
     * @param chargeTimeCount the value for device.chargeTimeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setChargeTimeCount(String chargeTimeCount) {
        this.chargeTimeCount = chargeTimeCount == null ? null : chargeTimeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.chargeTimesCount
     *
     * @return the value of device.chargeTimesCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Integer getChargeTimesCount() {
        return chargeTimesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.chargeTimesCount
     *
     * @param chargeTimesCount the value for device.chargeTimesCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setChargeTimesCount(Integer chargeTimesCount) {
        this.chargeTimesCount = chargeTimesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.chargeFeeCount
     *
     * @return the value of device.chargeFeeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Double getChargeFeeCount() {
        return chargeFeeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.chargeFeeCount
     *
     * @param chargeFeeCount the value for device.chargeFeeCount
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setChargeFeeCount(Double chargeFeeCount) {
        this.chargeFeeCount = chargeFeeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.deviceType
     *
     * @return the value of device.deviceType
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Boolean getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.deviceType
     *
     * @param deviceType the value for device.deviceType
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setDeviceType(Boolean deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.chargeRate
     *
     * @return the value of device.chargeRate
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Integer getChargeRate() {
        return chargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.chargeRate
     *
     * @param chargeRate the value for device.chargeRate
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setChargeRate(Integer chargeRate) {
        this.chargeRate = chargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.created_at
     *
     * @return the value of device.created_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.created_at
     *
     * @param created_at the value for device.created_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.updated_at
     *
     * @return the value of device.updated_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.updated_at
     *
     * @param updated_at the value for device.updated_at
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deviceID=").append(deviceID);
        sb.append(", workingStatu=").append(workingStatu);
        sb.append(", chargeStatu=").append(chargeStatu);
        sb.append(", chargeTimeCount=").append(chargeTimeCount);
        sb.append(", chargeTimesCount=").append(chargeTimesCount);
        sb.append(", chargeFeeCount=").append(chargeFeeCount);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", chargeRate=").append(chargeRate);
        sb.append(", created_at=").append(created_at);
        sb.append(", updated_at=").append(updated_at);
        sb.append("]");
        return sb.toString();
    }
}