package com.project.smartcharge.mapper;

import com.project.smartcharge.pojo.Bill;
import com.project.smartcharge.pojo.BillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    long countByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int deleteByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int deleteByPrimaryKey(Integer billID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int insert(Bill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int insertSelective(Bill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    List<Bill> selectByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    Bill selectByPrimaryKey(Integer billID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByExampleSelective(@Param("row") Bill row, @Param("example") BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByExample(@Param("row") Bill row, @Param("example") BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByPrimaryKeySelective(Bill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByPrimaryKey(Bill row);
}