package com.project.smartcharge.mapper;

import com.project.smartcharge.pojo.Carinfo;
import com.project.smartcharge.pojo.CarinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    long countByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int deleteByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int deleteByPrimaryKey(Integer carID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int insert(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int insertSelective(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    List<Carinfo> selectByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    Carinfo selectByPrimaryKey(Integer carID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByExampleSelective(@Param("row") Carinfo row, @Param("example") CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByExample(@Param("row") Carinfo row, @Param("example") CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByPrimaryKeySelective(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Fri Jun 02 17:49:13 CST 2023
     */
    int updateByPrimaryKey(Carinfo row);

    int updateCarRankByChargeModeAndCarRank(@Param("carRank") Integer carRank,
                                            @Param("chargeMode") boolean chargeMode);

}