package com.project.smartcharge.mapper;

import com.project.smartcharge.pojo.Device;
import com.project.smartcharge.pojo.DeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    long countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int deleteByPrimaryKey(Integer deviceID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int insert(Device row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int insertSelective(Device row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    Device selectByPrimaryKey(Integer deviceID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int updateByExampleSelective(@Param("row") Device row, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int updateByExample(@Param("row") Device row, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int updateByPrimaryKeySelective(Device row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Wed Jun 07 14:47:42 CST 2023
     */
    int updateByPrimaryKey(Device row);
}